
project_id = "nhlzeuxavyzxbyjllnaf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Define functions with proper format
[functions.get-cards]
verify_jwt = false

[functions.get-matches]
verify_jwt = false

[functions.get-messages]
verify_jwt = false

[functions.record-swipe]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.delete-connection]
verify_jwt = false
