
project_id = "nhlzeuxavyzxbyjllnaf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

# We need to tell Supabase Studio about our new delete-connection function
[[functions]]
name = "get-cards"
verify_jwt = false

[[functions]]
name = "get-matches"
verify_jwt = false

[[functions]]
name = "get-messages"
verify_jwt = false

[[functions]]
name = "record-swipe"
verify_jwt = false

[[functions]]
name = "send-message"
verify_jwt = false

[[functions]]
name = "delete-connection"
verify_jwt = false
