// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhlzeuxavyzxbyjllnaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5obHpldXhhdnl6eGJ5amxsbmFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4ODQwNzMsImV4cCI6MjA1NjQ2MDA3M30.zLb7smZlk95QkQRulo35E8pWY04sDwABALrZHPdCm0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);